version:  '3.8'
services:
  notebooks:
    build:
      dockerfile: Dockerfile 
      context: .
    image: uk-open3r:0.0.1
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data   
    ports:
      - 8888:8888
    container_name: uk_open3r
    command: 'start-notebook.sh'
